### ISSUE TITLE
use official srgssr api (if possible)

### ISSUE THREAD

**Issue by meierfra** [ManBehindMooN/kodi_plugin_video_srf_ch_replay#1]
the original plugin uses an undocumented API. But there seems to be an official API from SRG -> https://developer.srgssr.ch/apis/srgssr-video
I don't know how trivial it is to use this API, from a first look it looks like an API key has to be optained, and may be there are other problems. 
But if it is possible, I would recommend to use it, since an undocumented/unofficial API is prone to change without notice and break the plugin.

**Comment by meierfra** [comment]
on a sidenote: i would prefer using the python 'requests' http library [1]. Since it is easier to use than the now used urllib 
[1] https://pypi.org/project/requests

**Comment by ManBehindMooN** [comment]
done with https://github.com/ManBehindMooN/kodi_plugin_video_srgssr_ch_replay
