### ISSUE TITLE
Loading of content very slow

### ISSUE THREAD

**Issue by loadamasta** [ManBehindMooN/kodi_plugin_video_srf_ch_replay#3]
Loading of content under a letter, for example "n" takes more than one minute to load. But there are only 8 items to load.

**Comment by ManBehindMooN** [comment]
hi @loadamasta 
Thanks for opening this issue. This add-on was deprecated a while back and seems to be broken now. The unofficial API has changed and we are going to mark this add-on as broken within the next couple of days (see https://github.com/ManBehindMooN/kodi_plugin_video_srf_ch_replay/pull/4). Please move to the new add-on https://kodi.tv/addons/matrix/plugin.video.srgssr_ch_replay. If you have any issues with the new one, then please let us know. Thank you and happy streaming.

**Comment by ManBehindMooN** [comment]
hi @loadamasta,
I quickly fixed the addon (see https://github.com/ManBehindMooN/kodi_plugin_video_srf_ch_replay/pull/5). This might solve your problem but this will be the last fix. As soon as there is another issue this add-on will be marked as broken and you definitely have to move to the new one. The add-on should be in the official repo in a couple of days. Update & enjoy!

**Comment by ManBehindMooN** [comment]
hi @loadamasta,
2.0.3 is in the repo. I tried it on my old slow Android TV and the "n" letter opened quiet fast. If you experience slow behavior you can change manually (see PR) the URL https://il.srgssr.ch/integrationlayer/2.0/srf/showList/tv/alphabetical?vector=portalplay&pageSize=unlimited&onlyActiveShows=false (500+ entries) within the addon.py file and change the onlyActiveShows=true (200+ entries).

**Comment by loadamasta** [comment]
Hi,

 

Thank you very much for your efforts.

 

 I will give the new addon a try.

 

Best regards,

Loadamasta

 

 

 

Von: ManBehindMooN ***@***.***>
Antworten an: ManBehindMooN/kodi_plugin_video_srf_ch_replay ***@***.***>
Datum: Samstag, 5. März 2022 um 13:01
An: ManBehindMooN/kodi_plugin_video_srf_ch_replay ***@***.***>
Cc: loadamasta ***@***.***>, Mention ***@***.***>
Betreff: Re: [ManBehindMooN/kodi_plugin_video_srf_ch_replay] Loading of content very slow (Issue #3)
Neu gesendet von: ***@***.***>
Neu gesendet am: Sat, 5 Mar 2022 12:01:08 +0000 (UTC)

 

hi @loadamasta,
2.0.3 is in the repo. I tried it on my old slow Android TV and the "n" letter opened quiet fast. If you experience slow behavior you can change manually (see PR) the URL https://il.srgssr.ch/integrationlayer/2.0/srf/showList/tv/alphabetical?vector=portalplay&pageSize=unlimited&onlyActiveShows=false (500+ entries) within the addon.py file and change the onlyActiveShows=true (200+ entries).

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
